spring:
  profiles:
    active: dev #定义默认的生效环境
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/br?useUnicode=true&characterEncoding=utf-8  # 数据库连接地址
    username: root  # 数据库用户名
    password: edceez3@5  # 数据库连接密码
    type: com.zaxxer.hikari.HikariDataSource # 指定数据源的类型
  jpa: # 定义JPA的相关配置项
    show-sql: true                                # 显示执行的SQL
    properties: # 配置JPA属性
      hibernate.format_sql: true                 # 格式化SQL
      hibernate.cache.use_second_level_cache: true   # 二级缓存配置
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: true      # 查询缓存
      hibernate.enable_lazy_load_no_trans: true # 在没有事务的情况下允许懒加载
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: update                            # 自动DDL更新
    open-in-view: true
  rabbitmq:
#      addresses: localhost     # rabbitmq服务主机名称
      host: 127.0.0.1               # 主机名称
      port: 5672                    # 端口号
      username: guest              # 用户名
      password: guest                 # 密码
      virtual-host: /                 # 虚拟主机

  redis: # Redis相关配置
    host: 127.0.0.1    # 主机名称
    port: 6379              # 端口号
#    password: mldnjava      # 认证密码
    timeout: 1000         # 连接超时时间
    database: 0         # 默认数据库
    jedis:
      pool:               # 连接池配置
        max-active: 10    # 最大连接数
        max-idle: 8       # 最大维持连接数
        min-idle: 2     # 最小维持连接数
        max-wait: 100 # 最大等待连接超时时间
server:
  port: 7070  #此处设置服务的访问端口设置
  servlet:
    context-path: /br #定义ContextPath路径
  messages: # 定义资源文件，多个资源文件使用“,”分割
    basename: i18n/Messages
logging:
  level:
    root: "info"
    com.boransolution.brboot: "debug"
  file:
    path: D:\log
    name: brboot.log
---
spring:
  config:
    activate:
      on-profile: beta
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/br?useUnicode=true&characterEncoding=utf-8  # 数据库连接地址
    username: root  # 数据库用户名
    password: edceez3@5  # 数据库连接密码
    type: com.zaxxer.hikari.HikariDataSource # 指定数据源的类型
  jpa: # 定义JPA的相关配置项
    show-sql: true                                # 显示执行的SQL
    properties: # 配置JPA属性
      hibernate.format_sql: true                 # 格式化SQL
      hibernate.cache.use_second_level_cache: true   # 二级缓存配置
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: true      # 查询缓存
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: update                            # 自动DDL更新
server:
  port: 8080  #此处设置服务的访问端口设置
  servlet:
    context-path: /br #定义ContextPath路径
  messages: # 定义资源文件，多个资源文件使用“,”分割
    basename: i18n/Messages


---
spring:
  config:
    activate:
      on-profile: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/br?useUnicode=true&characterEncoding=utf-8  # 数据库连接地址
    username: root  # 数据库用户名
    password: edceez3@5  # 数据库连接密码
    type: com.zaxxer.hikari.HikariDataSource # 指定数据源的类型
  jpa: # 定义JPA的相关配置项
    show-sql: true                                # 显示执行的SQL
    properties: # 配置JPA属性
      hibernate.format_sql: true                 # 格式化SQL
      hibernate.cache.use_second_level_cache: true   # 二级缓存配置
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: true      # 查询缓存
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: update                            # 自动DDL更新
server:
  port: 80  #此处设置服务的访问端口设置
  servlet:
    context-path: /br #定义ContextPath路径
  messages: # 定义资源文件，多个资源文件使用“,”分割
    basename: i18n/Messages

