spring:
  profiles:
    active: dev #定义默认的生效环境
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 7070  #此处设置服务的访问端口设置
  servlet:
    context-path: /br #定义ContextPath路径
  messages: # 定义资源文件，多个资源文件使用“,”分割
    basename: i18n/Messages


---
spring:
  config:
    activate:
      on-profile: beta
server:
  port: 8080  #此处设置服务的访问端口设置
  servlet:
    context-path: /br #定义ContextPath路径
  messages: # 定义资源文件，多个资源文件使用“,”分割
    basename: i18n/Messages


---
spring:
  config:
    activate:
      on-profile: product
server:
  port: 80  #此处设置服务的访问端口设置
  servlet:
    context-path: /br #定义ContextPath路径
  messages: # 定义资源文件，多个资源文件使用“,”分割
    basename: i18n/Messages

